In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('/Users/alishbahiqbal/Desktop/c2v_pytorch/Code2vec_Pytorch_pipeline/csvs/non_divisible_marks.csv')
df

     FileName   Marks
0       648.c   5.670
1       395.c   6.998
2      1346.c   6.480
3       801.c  18.000
4       802.c  18.000
...       ...     ...
2241    650.c   5.400
2242    649.c   5.400
2243    652.c   5.400
2244    651.c   5.400
2245   1498.c   4.374

[2246 rows x 2 columns]

In [50]:
scaled_class = []
for m in df.Marks:
    if m >= 1.08 and m <= 2.666:
        scaled_class += [1]
#         print(m,1)
    elif m>2.666 and m<=6.666:
        scaled_class += [2]
#         print(m,2)
    elif m>6.666:
        scaled_class += [3]
#         print(m,3)

In [51]:
df = df.drop('Marks', axis=1)
df['Marks'] = scaled_class
df

     FileName  Marks
0       648.c      2
1       395.c      3
2      1346.c      2
3       801.c      3
4       802.c      3
...       ...    ...
2241    650.c      2
2242    649.c      2
2243    652.c      2
2244    651.c      2
2245   1498.c      2

[2246 rows x 2 columns]

In [52]:
df.to_csv('/Users/alishbahiqbal/Desktop/c2v_pytorch/Code2vec_Pytorch_pipeline/csvs/non_divisible_marks.csv', index=False)

In [47]:
import os

# folder path
dir_path = '/Users/alishbahiqbal/Desktop/c2v_pytorch/Code2vec_Pytorch_pipeline/data/non_divisible'
count = 0
dt = {}
# Iterate directory
# for path in os.listdir(dir_path):
for path in os.listdir(dir_path):
    # check if current path is a file
    direct = os.path.join(dir_path, path)
    if os.path.isdir(direct):
        print(path)
        path_list = list(set(path))
        
        for p in os.listdir( os.path.join(dir_path, path)):
            filee = os.path.join(direct, p)
            if os.path.isfile(filee):
                count += 1
        print('File count:', count)
        dt[float(path)] = count
#         count = 0

05.67
File count: 1
06.998
File count: 2
06.48
File count: 3
18.00
File count: 9
04.32
File count: 10
08.00
File count: 151
14.04
File count: 152
03.936
File count: 155
03.24
File count: 156
14.58
File count: 158
08.64
File count: 159
03.15
File count: 161
07.874
File count: 164
05.832
File count: 166
04.80
File count: 170
06.666
File count: 322
04.86
File count: 327
10.666
File count: 428
08.40
File count: 430
10.80
File count: 431
12.00
File count: 445
09.334
File count: 544
01.20
File count: 550
03.498
File count: 552
04.724
File count: 554
02.666
File count: 786
06.00
File count: 790
02.834
File count: 791
07.776
File count: 794
11.81
File count: 795
13.334
File count: 842
05.334
File count: 1117
18.666
File count: 1273
01.08
File count: 1278
04.96
File count: 1279
20.00
File count: 1336
04.00
File count: 1611
01.334
File count: 2204
07.20
File count: 2208
17.334
File count: 2224
12.246
File count: 2225
12.636
File count: 2226
02.916
File count: 2229
03.60
File count: 2236
06.298
File count: 2237
07.56
File count: 2241
05.40
File count: 2245
04.374
File count: 2246

In [39]:
for key, value in sorted(dt.items(), key=lambda x: x[0]): 
    print("{} : {}".format(key, value))

1.08 : 1278
1.2 : 550
1.334 : 2204
2.666 : 786
2.834 : 791
2.916 : 2229
3.15 : 161
3.24 : 156
3.498 : 552
3.6 : 2236
3.936 : 155
4.0 : 1611
4.32 : 10
4.374 : 2246
4.724 : 554
4.8 : 170
4.86 : 327
4.96 : 1279
5.334 : 1117
5.4 : 2245
5.67 : 1
5.832 : 166
6.0 : 790
6.298 : 2237
6.48 : 3
6.666 : 322
6.998 : 2
7.2 : 2208
7.56 : 2241
7.776 : 794
7.874 : 164
8.0 : 151
8.4 : 430
8.64 : 159
9.334 : 544
10.666 : 428
10.8 : 431
11.81 : 795
12.0 : 445
12.246 : 2225
12.636 : 2226
13.334 : 842
14.04 : 152
14.58 : 158
17.334 : 2224
18.0 : 9
18.666 : 1273
20.0 : 1336

In [42]:
# 1.08 : 5
# 1.2 : 6
# 1.334 : 593
# 2.666 : 232

#      836

# 2.834 : 1
# 2.916 : 3
# 3.15 : 2
# 3.24 : 1
# 3.498 : 2
# 3.6 : 7
# 3.936 : 3
# 4.0 : 275
# 4.32 : 1
# 4.374 : 1
# 4.724 : 2
# 4.8 : 4
# 4.86 : 5
# 4.96 : 1
# 5.334 : 275
# 5.4 : 4
# 5.67 : 1
# 5.832 : 2
# 6.0 : 4
# 6.298 : 1
# 6.48 : 1
# 6.666 : 152
    
#     # 748
    
# 6.998 : 1
# 7.2 : 4
# 7.56 : 4
# 7.776 : 3
# 7.874 : 3
# 8.0 : 141
# 8.4 : 2
# 8.64 : 1
# 9.334 : 99
# 10.666 : 101
# 10.8 : 1
# 11.81 : 1
# 12.0 : 14
# 12.246 : 1
# 12.636 : 1
# 13.334 : 47
# 14.04 : 1
# 14.58 : 2
# 17.334 : 16
# 18.0 : 6
# 18.666 : 156
# 20.0 : 57

#     662